{% set name = "quicfire-tools" %}
{% set version = "0.11.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quicfire_tools-{{ version }}.tar.gz
  sha256: 91456ccc7148e3327d0ac75e6035d5a022a97fe0bc520b5257845c9453a49b1a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - dask
    - dask-expr
    - netcdf4
    - numpy
    - pandas
    - pydantic >=2
    - pyproj
    - scipy
    - zarr

test:
  imports:
    - quicfire_tools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/silvxlabs/quicfire-tools
  summary: Input and output management tools for the QUIC-Fire fire model
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amarcozzi
